### PR TITLE
Reduce RegExp complexity

### PR DESCRIPTION
**Pull request by therealklanni**

### CODE REVIEW

**Comment by jsdevel** [comment]
@therealklanni I'm thinking I may reject this, as the original was clearer IMO.  The proposed regex has unintended consequences.

**Comment by therealklanni** [comment]
I'm not sure what you mean. The proposed expression is exactly the same semantically. 

`.* === [/s/S]`

You're saying "everything that's a space AND everything that's not a space" which is semantically the same as "anything". If you wanted to use `.+` instead of `.*` that's up to you, but I don't see it being necessary.

**Comment by jsdevel** [comment]
Changing this `[^)]+` to this`.*` feels like it would match the following:

`function()function(`

**Comment by jsdevel** [comment]
Also, `.` doesn't match newline characters, so `[\s\S]` does _not_ mean the same thing as `.` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

**Comment by therealklanni** [comment]
Regardless if `[\s\S]` would also capture newlines, that's the end of your expression anyway. Clearly you don't care what follows after `function()`, so what's the point? Technically, you should just leave out the last `.*` in that case.

As far as the `[^)]+` again it's semantically the same as `.+\)`. If you want it not to be greedy, you can add a `?`, like `.+?\)`, but `function()function()` would throw a syntax error long before you got to that point anyway, so it's meaningless to add the `?`.

So, while you may be correct that `[\s\S]` would match newlines (not going to bother to check and just take your word on it), and `.*\)` would match `function()function()`, it's completely moot because of the rest of the expression and the context.

So again, I would say replace `*` with `+` if you want it to match at least one character (I'm not convinced it matters, though), but other than that `/(function.*\)).*/m` is semantically the same as your original regex, but it's more clear what it's matching and it's more succinct.

So if you want to reject the change it, that's up to you, it's your project. :octopus:

**Comment by jsdevel** [comment]
I completely forgot this was here @therealklanni :smile: With es6 this package is likely useless now anyway.

**Pull request closed without merging**
